services:
  api:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: 10m

  importer:
    image: johnflix-api-api:latest
    volumes:
      - .:/app
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: 10m

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  data: