version: "3.1"

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: 10m

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: