# Generated by Django 3.0.5 on 2022-05-24 09:58

from django.db import migrations, models
import django.db.models.deletion
import shared.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('cover', models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cover', models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path)),
                ('hidden', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('cover', models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path)),
                ('hidden', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.Content')),
                ('genre', models.ManyToManyField(to='content.Genre')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cover', models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path)),
                ('hidden', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=36, unique=True)),
                ('number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.Media')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=36, unique=True)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('cover', models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path)),
                ('media', models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path)),
                ('duration', models.FloatField(default=0)),
                ('frames', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.Season')),
                ('tag', models.ManyToManyField(to='content.Tag')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
