# Generated by Django 3.0.5 on 2022-06-27 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.helper


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0034_auto_20220620_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='content',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Season'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subtitle'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AlterField(
            model_name='media',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subtitle'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Episode'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Movie'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='season',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Media'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='vtt',
            field=models.FileField(upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
    ]
