# Generated by Django 3.0.5 on 2023-11-05 12:31

from django.db import migrations, models
import shared.helper


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0168_auto_20230927_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-created_date'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_date'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='movie',
            name='metadata',
            field=models.BooleanField(default=False, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='genre',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='cover_credit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cover_credit'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='media',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='_description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='director_link'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.FloatField(default=0, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='embed',
            field=models.TextField(blank=True, default='', null=True, verbose_name='embed'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='content.Genre', verbose_name='_genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='height',
            field=models.FloatField(default=0, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='prizes',
            field=models.TextField(blank=True, null=True, verbose_name='prizes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tag',
            field=models.ManyToManyField(blank=True, to='content.Tag', verbose_name='_tag'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='triggers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='triggers'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='width',
            field=models.FloatField(default=0, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='photocollection',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='vtt',
            field=models.FileField(upload_to=shared.helper.Helper.get_file_path),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=shared.helper.Helper.get_file_path, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='custom_letter',
            field=models.BooleanField(default=False, verbose_name='custom_letter'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='genre',
            field=models.BooleanField(default=False, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='order'),
        ),
    ]
