name: ReleasePRD

on:
  push:
    branches: [ main ]

env:
  CONTAINER_IMAGE: ${{ secrets.CONTAINER_REGISTRY_IMAGE }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOC_HUB_USR }}
        password: ${{ secrets.DOC_HUB_PWD }}

    - name: Build and tag the image
      id: build-image
      run: |
        docker build . --file Dockerfile --tag $CONTAINER_IMAGE
        
    - name: Config aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SEC }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push into ECR
      run: |
        docker push $CONTAINER_IMAGE
        
    - name: Download Task Definition
      run: |
        aws ecs describe-task-definition --task-definition johnfilx \
        --query taskDefinition > task-definition-johnfilx.json

    - name: Add Image ID to Task Definition
      id: task-def-johnfilx
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-johnfilx.json
        container-name: johnflix
        image: $CONTAINER_IMAGE

    - name: Deploy ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-johnfilx.outputs.task-definition }}
        service: johnflix
        cluster: production
        wait-for-service-stability: false