name: Release

on:
  push:
    branches: [main]

env:
  CONTAINER_IMAGE: chr0nu5/base:johnflix-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOC_HUB_USR }}
          password: ${{ secrets.DOC_HUB_PWD }}

      - name: Build and tag the image
        run: |
          docker build . --file Dockerfile --tag $CONTAINER_IMAGE

      - name: Push the image
        run: |
          docker push $CONTAINER_IMAGE
